import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./_component/UserProfile";
import Sidebar from "./_component/Sidebar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-body`}>
        <div className="flex">

          <div className="w-[20%]">
            <Sidebar />
          </div>
          

          <div className="w-[80%]">
            <Navbar />
            {children}
          </div>
        </div>
        
      </body>
    </html>
  );
}
